
import argparse
import json
import logging
import multiprocessing as mp
from pathlib import Path

import nibabel as nib
import numpy as np
import pandas as pd
from loguru import logger
from tqdm import tqdm

from src.utils.coords_conversion import image_id_to_world_y, map_LR_zx_to_world_xz
from src.utils.helpers import get_n_available_cpus
from src.utils.logger_setup import setup_logging

logging.getLogger("h5py").setLevel(logging.WARNING)

LR_SLICE_WORLD_Y_START = -70.02
LR_SLICE_WORLD_Y_STEP = 0.02

DEFAULT_INPUT_DIR = Path(
    "data/output/full_lr_predictions/allCA_best_model_128_96_smooth_b05_k5_roi"
)
DEFAULT_BBOX_DIR = Path("data/input/all_regions/low_res")
DEFAULT_FULL_LR_DIR = Path("data/raw/low_res")
DEFAULT_OUTPUT_DIR = Path(
    "data/output/mesoscale_reconstruction/allCA_best_model_128_96_smooth_b05_k5_roi"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Build a 3D point-cloud CSV from per-slice sampled density predictions."
        ),
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=DEFAULT_INPUT_DIR,
        help=(
            "Predicted point folder inside .npy files, "
            "generated by predict_on_lr_wsi_folder.py."
        ),
    )
    parser.add_argument(
        "--bbox-dir",
        type=Path,
        default=DEFAULT_BBOX_DIR,
        help=(
            "Folder containing {wsi_id}_bbox_lr.json files "
            "with x_min and z_min offsets."
        ),
    )
    parser.add_argument(
        "--full-lr-dir",
        type=Path,
        default=DEFAULT_FULL_LR_DIR,
        help=(
            "Folder containing the full set of LR slices "
            "(pm{wsi_id}o.mnc), used to extract the world affine transform."
        ),
    )
    parser.add_argument(
        "--insert-ca-areas",
        action="store_true",
        help="Insert CA area column inside the created CSV file.",
    )
    parser.add_argument(
        "--lr-slice-world-y-start",
        type=float,
        default=LR_SLICE_WORLD_Y_START,
        help="World-space y coordinate used as the LR slice index origin.",
    )
    parser.add_argument(
        "--lr-slice-world-y-step",
        type=float,
        default=LR_SLICE_WORLD_Y_STEP,
        help="World-space y spacing between consecutive LR slice IDs.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Where to save the point-cloud CSV.",
    )
    parser.add_argument(
        "--num-workers",
        type=int,
        default=get_n_available_cpus(exclude_current=True),
        help="Number of worker processes to use.",
    )

    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable DEBUG-level logging.",
    )
    return parser.parse_args()


def discover_files(
    input_dir: Path,
    bbox_dir: Path,
    full_lr_dir: Path,
    insert_ca: bool = False,
    lr_slice_world_y_start: float = LR_SLICE_WORLD_Y_START,
    lr_slice_world_y_step: float = LR_SLICE_WORLD_Y_STEP,
):
    """
    Discover prediction, bbox, and full LR files for each WSI.
    """

    wsi_entries = []

    for predicted_file in input_dir.glob("*_points_preds.npy"):
        wsi_id = predicted_file.stem.split("_")[0]
        bbox_file = bbox_dir / f"{wsi_id}_bbox_lr.json"
        full_lr_file = full_lr_dir / f"pm{wsi_id}o.mnc"

        if not bbox_file.exists():
            logger.warning(
                f"Skipping {wsi_id} because bbox file is missing: {bbox_file}"
            )
            continue

        if not full_lr_file.exists():
            logger.warning(
                f"Skipping {wsi_id} because full LR file is missing: {full_lr_file}"
            )
            continue

        # Optional CA area file
        if insert_ca:
            ca_area_file = input_dir / f"{wsi_id}_ca_areas.npy"

            if not ca_area_file.exists():
                logger.warning(
                    f"Skipping {wsi_id} because CA area file is missing: {ca_area_file}"
                )
                continue
        else:
            ca_area_file = None

        wsi_entries.append(
            {
                "wsi_id": wsi_id,
                "point_file": predicted_file,
                "bbox_file": bbox_file,
                "full_lr_file": full_lr_file,
                "ca_area_file": ca_area_file,
                "lr_slice_world_y_start": lr_slice_world_y_start,
                "lr_slice_world_y_step": lr_slice_world_y_step,
            }
        )

    return wsi_entries


def map_single_wsi(wsi_entry: dict) -> pd.DataFrame:
    """Create one point-cloud DataFrame from a single WSI prediction entry."""

    wsi_id = wsi_entry["wsi_id"]
    point_file = wsi_entry["point_file"]
    bbox_file = wsi_entry["bbox_file"]
    full_lr_file = wsi_entry["full_lr_file"]
    ca_area_file = wsi_entry["ca_area_file"]
    lr_slice_world_y_start = wsi_entry["lr_slice_world_y_start"]
    lr_slice_world_y_step = wsi_entry["lr_slice_world_y_step"]

    logger.info(
        f"Processing WSI {wsi_id} with point file {point_file}, "
        f"bbox file {bbox_file}, and full LR file {full_lr_file}"
    )

    # Load predicted point
    predicted_points = np.load(point_file)  # Shape (H, W, C)
    ca_areas = np.load(ca_area_file) if ca_area_file is not None else None

    if ca_areas is not None:
        assert predicted_points.shape[:2] == ca_areas.shape, (
            "Predicted points and CA areas must have the same spatial dimensions"
        )

    # Load bbox info
    with open(bbox_file, "r") as f:
        bbox_info = json.load(f)

    # Load LR affine
    lr_img_data = nib.load(str(full_lr_file))
    lr_affine = np.asarray(lr_img_data.affine, dtype=float)

    # Get indices of points where any channel is non-zero
    z_indices, x_indices = np.nonzero(predicted_points.sum(axis=-1) > 0)
    points_to_map_zx = np.column_stack((z_indices, x_indices))

    # Flip Z axis
    img_height = predicted_points.shape[0]
    points_to_map_flipped_zx = points_to_map_zx.copy()
    points_to_map_flipped_zx[:, 0] = img_height - 1 - points_to_map_zx[:, 0]

    # Map to global coord then to world coordinates
    global_points_zx = points_to_map_flipped_zx + np.array(
        [bbox_info["z_min"], bbox_info["x_min"]]
    )
    world_xz = map_LR_zx_to_world_xz(global_points_zx, lr_affine)

    y_world = image_id_to_world_y(
        wsi_id,
        lr_slice_world_y_start,
        lr_slice_world_y_step,
    )

    # Process each point and assemble output data
    output_points = []
    for world_point, local_point in zip(world_xz, points_to_map_zx):
        channel_values = predicted_points[local_point[0], local_point[1], :]

        ca_value = (
            ca_areas[local_point[0], local_point[1]] if ca_areas is not None else None
        )

        for channel_idx, value in enumerate(channel_values):
            if value > 0:
                output_points.append(
                    {
                        "world_x": round(world_point[0], 4),
                        "world_y": round(y_world, 4),
                        "world_z": round(world_point[1], 4),
                        "channel": channel_idx,
                        "count": value,
                        "ca_area": ca_value,
                    }
                )

    pandas_df = pd.DataFrame(output_points)

    return pandas_df


def map_all_wsis(wsi_entries: list, num_workers: int = 1) -> pd.DataFrame:
    """
    Process all WSI entries and combine their point clouds into a single DataFrame.
    """
    if num_workers <= 1:
        all_dfs = [
            map_single_wsi(wsi_entry)
            for wsi_entry in tqdm(wsi_entries, desc="Mapping WSIs")
        ]
    else:
        with mp.Pool(processes=num_workers) as pool:
            all_dfs = list(
                tqdm(
                    pool.imap(map_single_wsi, wsi_entries),
                    total=len(wsi_entries),
                    desc="Mapping WSIs",
                )
            )

    combined_df = pd.concat(all_dfs, ignore_index=True)
    return combined_df



def main():
    args = parse_args()
    setup_logging(debug=args.debug)

    input_dir = args.input_dir
    bbox_dir = args.bbox_dir
    full_lr_dir = args.full_lr_dir
    insert_ca_areas = args.insert_ca_areas
    output_dir = args.output_dir
    num_workers = args.num_workers

    # Discover files
    wsi_entries = discover_files(
        input_dir,
        bbox_dir,
        full_lr_dir,
        insert_ca_areas,
        lr_slice_world_y_start=args.lr_slice_world_y_start,
        lr_slice_world_y_step=args.lr_slice_world_y_step,
    )

    if not wsi_entries:
        logger.error(
            "No valid WSI entries found. Please check your input directories and files."
        )
        return

    # Process data
    combined_df = map_all_wsis(wsi_entries, num_workers=num_workers)

    # Export CSV
    output_dir.mkdir(parents=True, exist_ok=True)
    csv_path = output_dir / "point_cloud.csv"
    combined_df.to_csv(csv_path, index=False)
    logger.info(f"Saved combined point cloud CSV to {csv_path}")


if __name__ == "__main__":
    main()
